<?php

namespace Database\Factories;

use App\Models\Branch;
use App\Models\Table;
use App\Models\Tenant;
use App\Support\Tenancy\TenantManager;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Table>
 */
class TableFactory extends Factory
{
    public function definition(): array
    {
        return [
            'tenant_id' => app(TenantManager::class)->id() ?? Tenant::factory(),
            'branch_id' => Branch::factory(),
            'dining_area_id' => null,
            'code' => 'Masa '.fake()->unique()->numberBetween(1, 200),
            'is_active' => true,
            // qr_token auto-generated by the model on create.
        ];
    }

    public function forBranch(Branch $branch): static
    {
        return $this->state(fn () => ['tenant_id' => $branch->tenant_id, 'branch_id' => $branch->id]);
    }
}
